[package]
authors = ["J/A <archer884@gmail.com>"]
name = "jiraq"
version = "0.1.0"

[dependencies]
clap = "1.4.7"
hyper = "0.6.15"
regex = "0.1.41"
rpassword = "0.1.0"
rustc-serialize = "0.3.16"
serde = "0.6.1"
serde_json = "0.6.0"
serde_macros = "0.6.1"
toml = "0.1.23"
